Repository reactjs-id/website, pull requests merged in 2020-10, with the labels that each got.

#3 👌 IMPROVE: dynamic title
  .env.example
  components/Page.tsx
  pages/_app.tsx
  pages/about.tsx
Labels: hacktoberfest-accepted

#11 ci: added GitHub Actions CI
  .github/workflows/ci.yml
  package.json
Labels: hacktoberfest-accepted

#8 chore: move variables theme
  components/AppProvider/index.tsx
  utils/theme.ts
Labels: hacktoberfest-accepted

#10 feat: add faq page
  pages/faq.tsx
Labels: hacktoberfest-accepted

#13 Migrating Footer Component
  components/Layout/Page.tsx
  components/layout/Footer.tsx
  package-lock.json
Labels: hacktoberfest-accepted

#16 chore(top-navigation): migrasi top-navigation
  components/Layout/NextChakraLink.tsx
  components/Layout/Page.tsx
  components/Layout/TopNavigation.tsx
  components/Ui/Logo.tsx
  pages/_app.tsx
  pages/about.tsx
  pages/index.tsx
  yarn.lock
Labels: hacktoberfest-accepted

#17 chore: generate sitemap for better SEO
  .env.example
  next-sitemap.js
  package.json
  yarn.lock
Labels: hacktoberfest-accepted

#18 chore: styling page header properly with home page and another page
  components/Layout/PageHeader.tsx
  pages/index.tsx
  public/topography-img.png
  utils/theme.ts
Labels: hacktoberfest-accepted

#21 refactor: cleanup UI components
  components/Content.module.css
  components/Content.tsx
  components/Layout/AppRoot.tsx
  components/Navigation.module.css
  components/Navigation.tsx
  components/helpers/AppProvider.tsx
  components/helpers/NextChakraLink.tsx
  components/helpers/index.ts
  components/layouts/AppRoot.tsx
  components/layouts/Content.tsx
  components/layouts/Footer.tsx
  components/layouts/Page.tsx
  components/layouts/PageBody.tsx
  components/layouts/PageHeader.tsx
  components/layouts/TopNavigation.tsx
  components/layouts/index.ts
  components/ui/Logo.tsx
  components/ui/index.ts
  pages/_app.tsx
  pages/about.tsx
  pages/faq.tsx
  pages/index.tsx
  utils/theme.ts
  yarn.lock
Labels: hacktoberfest-accepted

#22 chore(submit-a-talk) : migrate submit-a-talk page (#12)
  pages/submit-a-talk.tsx
Labels: hacktoberfest-accepted

#25 feat: migrate community page
  pages/community.tsx
Labels: hacktoberfest-accepted

#26 feat: migrate home page
  components/layouts/PageHeader.tsx
  components/ui/LinkButton.tsx
  components/ui/index.ts
  pages/index.tsx
  public/rumah-komunitas/logo.png
  public/rumah-komunitas/tshirt.jpg
  resources/learnings.json
  tsconfig.json
  utils/theme.ts
Labels: hacktoberfest-accepted

#28 chore: integrated with mdx
  components/layouts/PageBody.tsx
  components/layouts/markdown/Heading.tsx
  components/layouts/markdown/Link.tsx
  components/layouts/markdown/index.ts
  contents/community.mdx
  index.d.ts
  package.json
  pages/[markdownPage].tsx
  pages/community.tsx
  utils/mdxUtils.ts
  utils/theme.ts
  yarn.lock
Labels: enhancement, hacktoberfest-accepted

#27 add LearningPage
  components/layouts/Section.tsx
  components/learning/LearningCard.tsx
  components/ui/ArrowRightIcon.tsx
  components/ui/index.ts
  pages/learning.tsx
  public/robots.txt
  public/sitemap.xml
Labels: hacktoberfest-accepted

#32 fix: FOUC when render markdown contents
  next-env.d.ts
  package.json
  pages/[markdownPage].tsx
  utils/htmrTransform.tsx
  yarn.lock
Labels: bug
